web_title: React Blog

# logo
logo_title: Logo Title
logo_description: Logo Description

# sidebar
author: ReverseSacle
description: 知识书库 & 学习点滴

sidebar:
  avatar: avatar.jpg


############################### navigation ###############################

# 菜单目录最多只支持二级目录
nav_menu:
  home: / || home
  posts:
    default: / || pen
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  about: /about/ || user
  friend-links: /friend-links/ || heart
  # books: /books/ || clipboard
  # tools: /tools/ || paper-plane

# 工具目录最多只支持一级目录
nav_tool:
  searcher: search

############################### navigation ###############################